---
grails:
    profile: web
    codegen:
        defaultPackage: am.neovision
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@show.app.name@'
        version: '@show.app.version@'
        grailsVersion: '@show.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
#datasource:
#    pooled: true
#    jmxExport: true
#    dbCreate: "update"
#    url: "jdbc:mysql://localhost:3306/neovisiongrailsapp?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT"
#    driverClassName: "com.mysql.cj.jdbc.Driver"
#    dialect: org.hibernate.dialect.MySQL8Dialect
#    username: "root"
#    password: "root"





spring:
    jmx:
        unique-names: true
---
jwtExpireLength: 3600000

serverPassword: password

activateAccountUrl: http:localhost:4200/register/confirm/
resetPasswordUrl: http:localhost:4200/reset/password/
changePasswordUrl: http://localhost:4200/change/password/
contactUsUrl: help@neovision.am

#spring:
#    mail:
#        host: smtp.gmail.com
#        port: 587
#        properties:
#            mail:
#                smtp:
#                    starttls:
#                        enable: true
#                        required: true
#                    auth: true
#                    connectiontimeout: 5000
#                    timeout: 5000
#                    writetimeout: 5000
#        password: a12345678.
#        username: noreply.interma@gmail.com
---
grails:
    mail:
        host: "smtp.gmail.com"
        port: 465
        username: "abrahamyan.arman.94@gmail.com"
        password: "exnikner1214"
        props:
            mail.smtp.auth: "true"
            mail.smtp.socketFactory.port: "465"
            mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
            mail.smtp.socketFactory.fallback: "false"

---
